### ISSUE TITLE
TypeError: db is undefined

### ISSUE THREAD

**Issue by MawiaHL** [mdn/to-do-notifications#6] opened 2019-02-11 13:30 UTC
Is this a bug or an issue with the latest version of firefox?

**Comment by chrisdavidmills** [comment] 2019-02-11 13:33
I've just tried https://mdn.github.io/to-do-notifications/ in the latest Firefox Nightly, and it seems to work fine for me. Which version are you using? Also, are you trying to run it locally, or online?

**Comment by MawiaHL** [comment] 2019-02-11 14:56
I am using firefox 65.0 (64bit).

**Comment by teoli2003** [comment] 2022-08-16 08:42
I've been using this on Firefox for weeks (for different reasons), and this is working.

I'm closing this issue. If the problem is still there, feel free to reopen a new issue.

**Closed by teoli2003** 2022-08-16 08:42 UTC
